targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - lib/app/domain/models/**/*.dart
      freezed:
        generate_for:
          - lib/app/domain/models/**/*
